---
params:
    batch_size: 6
    epoch: 100
    lr: 0.0001
    decay: 1
    decay_step: 10

save:
    metapath: "D:/PureGaze-main/exp/Res50-PureGaze/"
    folder: eth
    name: eth
    step: 1

data:
    image: "D:/PureGaze-main/dataset/eth_256_train"
    label: "D:/PureGaze-main/dataset/eth_label_dict.pickle"
    header: True
    name: eth
    isFolder: False

pretrain: False
device: 0
reader: reader_adap
map: "D:/PureGaze-main/Masker/eth-masker.jpg"
