---
params:
    batch_size: 35
    epoch: 100
    lr: 0.001
    decay: 0
    decay_step: 10

save:
    metapath: "D:/PureGaze-main/exp/Res50-PureGaze/"
    folder: pure_gaze_
    name: eth
    step: 1

data:
    image: "D:/PureGaze-main/dataset/eth_256_train"
    label: "D:/PureGaze-main/dataset/eth_label_dict.pickle"
    latent: "D:/PureGaze-main/dataset/train_latents"
    header: True
    name: eth
    isFolder: False

val_data: 
    image: "D:/PureGaze-main/dataset/eth_256_val"
    label: "D:/PureGaze-main/dataset/eth_label_dict.pickle"
    latent: "D:/PureGaze-main/dataset/val_latents"
    header: True
    name: eth
    isFolder: False

pretrain: ''
device: 0
reader: reader_adap
map: "D:/PureGaze-main/Masker/eth-masker.jpg"
